# Generated by Django 4.1.1 on 2022-11-24 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0058_rename_discount_product_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='service',
            name='Discount',
            field=models.IntegerField(default=0),
        ),
    ]
