# Generated by Django 4.1.1 on 2022-11-24 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0059_alter_product_discount_alter_service_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Discount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='Discount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
