# Generated by Django 4.1.1 on 2022-11-28 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0060_alter_product_discount_alter_service_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='Mission_Title',
            field=models.CharField(blank=True, default='Mission', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='Vision_Title',
            field=models.CharField(blank=True, default='Vision', max_length=50, null=True),
        ),
    ]
