# Generated by Django 4.1.1 on 2022-11-28 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0061_about_mission_title_about_vision_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='Mission',
            field=models.TextField(blank=True, null=True),
        ),
    ]
