# Generated by Django 4.1.1 on 2022-12-12 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0062_alter_about_mission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='Whatsapp',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
