# Generated by Django 4.1.4 on 2022-12-15 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0063_alter_enquiry_whatsapp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appbnr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField(null=True)),
                ('Status', models.IntegerField(default=1)),
                ('AddedBy', models.IntegerField(default=0)),
                ('Ip', models.GenericIPAddressField(null=True)),
                ('Edited_Date', models.DateTimeField(null=True)),
                ('EditedBy', models.IntegerField(default=0)),
                ('EditedIp', models.GenericIPAddressField(null=True)),
                ('Caption', models.CharField(max_length=100)),
                ('Sub_Caption', models.CharField(max_length=100)),
                ('Button_Label', models.CharField(max_length=30)),
                ('Link', models.CharField(max_length=1000)),
                ('Banner_Image', models.ImageField(blank=True, null=True, upload_to='BannerImage')),
            ],
        ),
    ]
