# Generated by Django 4.1.4 on 2022-12-19 08:52

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0065_blog_apidate_blog_apitime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='Description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
