# Generated by Django 4.1.4 on 2022-12-30 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0066_alter_blog_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='Currency',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
