# Generated by Django 4.1.4 on 2022-12-30 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0067_theme_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Country', models.CharField(max_length=50)),
                ('Currency', models.CharField(max_length=50)),
                ('Currency_Code', models.CharField(max_length=10)),
            ],
        ),
    ]
