# Generated by Django 4.1.4 on 2022-12-30 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0069_alter_theme_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='Currency',
            field=models.CharField(default=2, max_length=10),
            preserve_default=False,
        ),
    ]
